# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(337, 391)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output_lbl = QtWidgets.QLabel(self.centralWidget)
        self.output_lbl.setText("")
        self.output_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_lbl.setObjectName("output_lbl")
        self.verticalLayout.addWidget(self.output_lbl)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.nine_btn = QtWidgets.QPushButton(self.centralWidget)
        self.nine_btn.setObjectName("nine_btn")
        self.gridLayout.addWidget(self.nine_btn, 1, 2, 1, 1)
        self.four_btn = QtWidgets.QPushButton(self.centralWidget)
        self.four_btn.setObjectName("four_btn")
        self.gridLayout.addWidget(self.four_btn, 2, 0, 1, 1)
        self.seven_btn = QtWidgets.QPushButton(self.centralWidget)
        self.seven_btn.setObjectName("seven_btn")
        self.gridLayout.addWidget(self.seven_btn, 1, 0, 1, 1)
        self.three_btn = QtWidgets.QPushButton(self.centralWidget)
        self.three_btn.setObjectName("three_btn")
        self.gridLayout.addWidget(self.three_btn, 3, 2, 1, 1)
        self.eight_btn = QtWidgets.QPushButton(self.centralWidget)
        self.eight_btn.setObjectName("eight_btn")
        self.gridLayout.addWidget(self.eight_btn, 1, 1, 1, 1)
        self.dot_btn = QtWidgets.QPushButton(self.centralWidget)
        self.dot_btn.setObjectName("dot_btn")
        self.gridLayout.addWidget(self.dot_btn, 4, 2, 1, 1)
        self.two_btn = QtWidgets.QPushButton(self.centralWidget)
        self.two_btn.setObjectName("two_btn")
        self.gridLayout.addWidget(self.two_btn, 3, 1, 1, 1)
        self.six_btn = QtWidgets.QPushButton(self.centralWidget)
        self.six_btn.setObjectName("six_btn")
        self.gridLayout.addWidget(self.six_btn, 2, 2, 1, 1)
        self.one_btn = QtWidgets.QPushButton(self.centralWidget)
        self.one_btn.setObjectName("one_btn")
        self.gridLayout.addWidget(self.one_btn, 3, 0, 1, 1)
        self.five_btn = QtWidgets.QPushButton(self.centralWidget)
        self.five_btn.setObjectName("five_btn")
        self.gridLayout.addWidget(self.five_btn, 2, 1, 1, 1)
        self.subtract_btn = QtWidgets.QPushButton(self.centralWidget)
        self.subtract_btn.setObjectName("subtract_btn")
        self.gridLayout.addWidget(self.subtract_btn, 2, 3, 1, 1)
        self.result_btn = QtWidgets.QPushButton(self.centralWidget)
        self.result_btn.setObjectName("result_btn")
        self.gridLayout.addWidget(self.result_btn, 4, 3, 1, 1)
        self.add_btn = QtWidgets.QPushButton(self.centralWidget)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 3, 3, 1, 1)
        self.multipl_btn = QtWidgets.QPushButton(self.centralWidget)
        self.multipl_btn.setObjectName("multipl_btn")
        self.gridLayout.addWidget(self.multipl_btn, 1, 3, 1, 1)
        self.zero_btn = QtWidgets.QPushButton(self.centralWidget)
        self.zero_btn.setObjectName("zero_btn")
        self.gridLayout.addWidget(self.zero_btn, 4, 0, 1, 2)
        self.clear_btn = QtWidgets.QPushButton(self.centralWidget)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 0, 0, 1, 1)
        self.inveter_btn = QtWidgets.QPushButton(self.centralWidget)
        self.inveter_btn.setObjectName("inveter_btn")
        self.gridLayout.addWidget(self.inveter_btn, 0, 1, 1, 1)
        self.percent_btn = QtWidgets.QPushButton(self.centralWidget)
        self.percent_btn.setObjectName("percent_btn")
        self.gridLayout.addWidget(self.percent_btn, 0, 2, 1, 1)
        self.div_btn = QtWidgets.QPushButton(self.centralWidget)
        self.div_btn.setObjectName("div_btn")
        self.gridLayout.addWidget(self.div_btn, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nine_btn.setText(_translate("MainWindow", "9"))
        self.four_btn.setText(_translate("MainWindow", "4"))
        self.seven_btn.setText(_translate("MainWindow", "7"))
        self.three_btn.setText(_translate("MainWindow", "3"))
        self.eight_btn.setText(_translate("MainWindow", "8"))
        self.dot_btn.setText(_translate("MainWindow", "."))
        self.two_btn.setText(_translate("MainWindow", "2"))
        self.six_btn.setText(_translate("MainWindow", "6"))
        self.one_btn.setText(_translate("MainWindow", "1"))
        self.five_btn.setText(_translate("MainWindow", "5"))
        self.subtract_btn.setText(_translate("MainWindow", "-"))
        self.result_btn.setText(_translate("MainWindow", "="))
        self.add_btn.setText(_translate("MainWindow", "+"))
        self.multipl_btn.setText(_translate("MainWindow", "x"))
        self.zero_btn.setText(_translate("MainWindow", "0"))
        self.clear_btn.setText(_translate("MainWindow", "C"))
        self.inveter_btn.setText(_translate("MainWindow", "+/-"))
        self.percent_btn.setText(_translate("MainWindow", "%"))
        self.div_btn.setText(_translate("MainWindow", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

